spring:
  application:
    name: orquestador

feign:
  client:
    config:
      default:
        connectTimeout: 1600000
        readTimeout: 1600000
        loggerLevel: basic
server:
  port: 10001

# Configuración de servicios
# aqui hago una llamada interna a un servicio
clienteservice:
  url: http://localhost:10001

# para llamada a microservicios externos
cuentaservice:
  url: http://localhost:10003
movimientosservice:
  url: http://localhost:10004